-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 01:01:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genre` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Same as id3_genre_id',
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_artist1_idx` (`artist_id` ASC),
  CONSTRAINT `fk_album_artist1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `artist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(450) NOT NULL,
  `title` VARCHAR(100) NULL,
  `year` INT(4) NULL,
  `genre_id` INT NOT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_music_genre_idx` (`genre_id` ASC),
  INDEX `fk_music_album1_idx` (`album_id` ASC),
  CONSTRAINT `fk_music_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_music_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Placeholder table for view `music_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_view` (`id` INT, `file_path` INT, `title` INT, `year` INT, `genre_id` INT, `album_id` INT, `genre` INT, `album` INT, `artist_id` INT, `artist` INT);

-- -----------------------------------------------------
-- View `music_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music_view`;
CREATE  OR REPLACE VIEW `music_view` AS 
	SELECT 
	music.*,
    genre.id as genre_id, 
	genre.name as genre, 
	album.id as album_id, 
	album.name as album, 
	artist.id as artist_id,
	artist.name as artist
	FROM music 
    JOIN genre ON genre.id = genre_id
        JOIN album ON album.id = album_id
        JOIN artist ON artist.id = album.artist_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
